import dataCache from "@/utils/dataCache";

export interface IndexItem {
  id: string;
  brand: string;
  model: string;
  category: string;
  type: string;
  product_path: string;
  product_name: string;
  product_description: string;
  relative_products: string;
  // Legacy fields for backward compatibility
  asset_id?: string;
  subcategory?: string;
  category_path?: string;
  file_name?: string;
  thumbnail_path?: string;
  image_path?: string;
  coordinates_path?: string;
  data_path?: string;
  description?: string;
  related_ids?: string[];
}

export interface CategoryGroup {
  name: string;
  subcategories: string[];
  items: IndexItem[];
}

export interface CategoryNode {
  name: string;
  children: Map<string, CategoryNode>;
  items: IndexItem[];
}

export const readIndexFromDrive = async (): Promise<IndexItem[]> => {
  // Check cache first
  if (dataCache.hasIndexData()) {
    console.log('[Cache] Using cached index data');
    return dataCache.getIndexData()!;
  }

  const rootFolderId = import.meta.env.VITE_DRIVE_ROOT_FOLDER_ID;
  if (!rootFolderId) {
    throw new Error('VITE_DRIVE_ROOT_FOLDER_ID environment variable is required. Please set it in your .env file.');
  }

  const { listFilesInFolder, getDriveDownloadUrl } = await import('./googleDrive');
  const files = await listFilesInFolder(rootFolderId);
  const indexFile = files.find(file => file.name.toLowerCase() === 'index.csv');
  if (!indexFile) {
    throw new Error('No index.csv file found in the root folder. Please upload an index.csv file to your Google Drive root folder.');
  }

  const downloadUrl = getDriveDownloadUrl(indexFile.id);
  if (!downloadUrl) {
    throw new Error('Failed to generate download URL. Please check your VITE_DRIVE_API_KEY.');
  }

  const res = await fetch(downloadUrl);
  if (!res.ok) throw new Error(`Failed to fetch index.csv: ${res.status} ${res.statusText}`);
  const csvContent = await res.text();
  if (!csvContent.trim()) throw new Error('index.csv file is empty. Please add data to the file.');

  const { parse } = await import('papaparse');
  const normalizeHeader = (h: string) => String(h || '').trim();
  
  // Parse CSV with headers
  const parsed = parse(csvContent, { 
    header: true, 
    skipEmptyLines: true,
    transformHeader: normalizeHeader
  });
  
  const rows = parsed.data as any[];
  console.log('Parsed CSV rows:', rows.length);
  console.log('CSV headers:', parsed.meta.fields);

  // Check if we have the new structure
  const hasNewStructure = parsed.meta.fields?.includes('brand') && 
                         parsed.meta.fields?.includes('model') && 
                         parsed.meta.fields?.includes('category') && 
                         parsed.meta.fields?.includes('type') && 
                         parsed.meta.fields?.includes('product_path') && 
                         parsed.meta.fields?.includes('product_name') && 
                         parsed.meta.fields?.includes('product_description') && 
                         parsed.meta.fields?.includes('relative_products');

  if (hasNewStructure) {
    // New CSV structure - use product_path as folder names
    const items: IndexItem[] = rows.map((row, index) => {
      const relativeProducts = row.relative_products || '';
      const productPath = row.product_path || '';
      const productName = row.product_name || '';
      const productDescription = row.product_description || '';
      
      // Auto-generate file paths based on folder structure
      // The system will look for these files in the Google Drive folder named after the product_path
      const autoGeneratedPaths = {
        file_name: productName,
        thumbnail_path: `${productPath}/thumbnail.png`, // Standard thumbnail name
        image_path: `${productPath}/${productName}.png`, // Product name as image
        coordinates_path: `${productPath}/coordinates.json`, // Standard coordinates file
        data_path: `${productPath}/data.csv`, // Standard data file
        description: productDescription,
        asset_id: (index + 1).toString().padStart(4, '0'),
        subcategory: row.type || '',
        category_path: `${row.category} > ${row.type}`
      };
      
      return {
        id: (index + 1).toString(),
        brand: row.brand || '',
        model: row.model || '',
        category: row.category || '',
        type: row.type || '',
        product_path: productPath,
        product_name: productName,
        product_description: productDescription,
        relative_products: relativeProducts, // Store the relative products with brackets
        // Auto-generated legacy paths for backward compatibility
        ...autoGeneratedPaths
      };
    });
    
    console.log('Processed items with new structure:', items.length);
    console.log('Products and their folders:', items.map(item => ({
      product_path: item.product_path,
      product_name: item.product_name,
      product_description: item.product_description,
      relative_products: item.relative_products,
      folder: item.product_path, // Each product has its own folder
      image: item.image_path,
      coordinates: item.coordinates_path,
      data: item.data_path
    })));
    
    // Cache the data
    dataCache.setIndexData(items);
    
    return items;
  } else {
    // Legacy CSV structure - try to parse as before
    console.log('Detected legacy CSV structure, attempting to parse...');
    const raw = parse(csvContent, { header: false, skipEmptyLines: false });
    const legacyRows: string[][] = (raw.data as any[])
      .filter(r => Array.isArray(r))
      .map(r => r.map((v: any) => (v == null ? '' : String(v))));

    const hasAssetPaths = (headers: string[]) => {
      const hs = headers.map(h => normalizeHeader(h).toLowerCase());
      const hasCoords = hs.includes('coordinates_path');
      const hasData = hs.includes('data_path');
      const hasAssetId = hs.includes('asset_id') || hs.includes('assetid') || hs.includes('id');
      return hasCoords && hasData && hasAssetId;
    };
    
    const hasMetadata = (headers: string[]) => {
      const hs = headers.map(h => normalizeHeader(h).toLowerCase());
      const required = ['category', 'subcategory'];
      const ok = required.every(k => hs.includes(k));
      const hasIdRef = hs.includes('asset_id') || hs.includes('assetid') || hs.includes('ref_id') || hs.includes('refid') || hs.includes('id');
      return ok && hasIdRef;
    };

    let header1Index = -1;
    for (let i = 0; i < legacyRows.length; i++) {
      const r = legacyRows[i];
      if (r.length === 0 || r.every(c => c === '')) continue;
      if (hasAssetPaths(r)) { header1Index = i; break; }
    }

    let header2Index = -1;
    if (header1Index >= 0) {
      for (let i = header1Index + 1; i < legacyRows.length; i++) {
        const r = legacyRows[i];
        if (!r || r.every(c => c === '')) continue;
        if (hasMetadata(r)) { header2Index = i; break; }
      }
    }

    if (!(header1Index >= 0 && header2Index > header1Index)) {
      throw new Error('index.csv must have the new structure with columns: brand, model, category, type, product_path, product_name, product_description, relative_products');
    }

    // Legacy parsing logic (simplified)
    const headers1 = legacyRows[header1Index].map(normalizeHeader);
    const headers2 = legacyRows[header2Index].map(normalizeHeader);
    
    const idIdx = headers1.findIndex(h => ['id', 'asset_id', 'assetId'].includes(h));
    const fileNameIdx = headers1.findIndex(h => h.toLowerCase() === 'file_name');
    const descIdx = headers1.findIndex(h => h.toLowerCase() === 'description');
    const imgIdx = headers1.findIndex(h => h.toLowerCase() === 'image_path');
    const coordsIdx = headers1.findIndex(h => h.toLowerCase() === 'coordinates_path');
    const dataIdx = headers1.findIndex(h => h.toLowerCase() === 'data_path');
    const thumbIdx = headers1.findIndex(h => h.toLowerCase() === 'thumbnail_path');
    
    const categoryIdx = headers2.findIndex(h => h.toLowerCase() === 'category');
    const subcategoryIdx = headers2.findIndex(h => h.toLowerCase() === 'subcategory');
    const refIdx = headers2.findIndex(h => ['asset_id','assetid','ref_id','refid','id'].includes(h.toLowerCase()));

    const pathMap = new Map<string, any>();
    for (let i = header1Index + 1; i < header2Index; i++) {
      const r = legacyRows[i];
      if (!r || r.every(c => c === '')) continue;
      const idVal = (r[idIdx] || '').trim();
      if (!idVal) continue;
      pathMap.set(idVal, {
        file_name: fileNameIdx >= 0 ? (r[fileNameIdx] || '').trim() : undefined,
        description: descIdx >= 0 ? (r[descIdx] || '').trim() : undefined,
        image_path: imgIdx >= 0 ? (r[imgIdx] || '').trim() : undefined,
        coordinates: coordsIdx >= 0 ? (r[coordsIdx] || '').trim() : undefined,
        data: dataIdx >= 0 ? (r[dataIdx] || '').trim() : undefined,
        thumbnail_path: thumbIdx >= 0 ? (r[thumbIdx] || '').trim() : undefined,
      });
    }

    const items: IndexItem[] = [];
    for (let i = header2Index + 1; i < legacyRows.length; i++) {
      const r = legacyRows[i];
      if (!r || r.every(c => c === '')) continue;
      const refId = (r[refIdx] || '').trim();
      const paths = refId ? pathMap.get(refId) : undefined;
      
      items.push({
        id: (i - header2Index - 1).toString(),
        brand: 'REVO', // Default brand for legacy data
        model: 'R-18HD & R-18HS', // Default model for legacy data
        category: (r[categoryIdx] || 'Uncategorized') as string,
        type: (r[subcategoryIdx] || '') as string,
        product_path: (paths && paths.file_name) || '',
        product_name: (paths && paths.file_name) || '',
        product_description: '',
        relative_products: '',
        // Legacy fields
        asset_id: refId,
        subcategory: (r[subcategoryIdx] || '') as string,
        file_name: (paths && paths.file_name) || '',
        thumbnail_path: (paths && paths.thumbnail_path) || '',
        image_path: (paths && paths.image_path) || '',
        coordinates_path: (paths && paths.coordinates) || '',
        data_path: (paths && paths.data) || '',
        description: (paths && paths.description) || '',
      });
    }

    // Cache the data
    dataCache.setIndexData(items);
    
    return items;
  }
};

export const groupByCategory = (items: IndexItem[]): CategoryGroup[] => {
  const categoryMap = new Map<string, CategoryGroup>();
  items.forEach(item => {
    if (!categoryMap.has(item.category)) {
      categoryMap.set(item.category, { name: item.category, subcategories: [], items: [] });
    }
    const category = categoryMap.get(item.category)!;
    // Use type as subcategory for new structure, fallback to subcategory for legacy
    const subcategory = item.type || item.subcategory || '';
    if (subcategory && !category.subcategories.includes(subcategory)) {
      category.subcategories.push(subcategory);
    }
    category.items.push(item);
  });
  return Array.from(categoryMap.values());
};

export const buildCategoryTree = (items: IndexItem[]): CategoryNode => {
  const root: CategoryNode = { name: 'root', children: new Map(), items: [] };
  items.forEach((item) => {
    const pathLevels = (item.category_path
      ? String(item.category_path).split('>').map((s: string) => s.trim()).filter(Boolean)
      : [item.category, item.type || item.subcategory].filter(Boolean)) as string[];
    let current = root;
    for (const level of pathLevels) {
      if (!current.children.has(level)) {
        current.children.set(level, { name: level, children: new Map(), items: [] });
      }
      current = current.children.get(level)!;
    }
    current.items.push(item);
  });
  return root;
};

export const getItemsByCategory = (items: IndexItem[], category: string): IndexItem[] => {
  return items.filter(item => item.category === category);
};

export const getItemsBySubcategory = (items: IndexItem[], category: string, subcategory: string): IndexItem[] => {
  return items.filter(item => item.category === category && (item.type === subcategory || item.subcategory === subcategory));
};

export const getItemsByType = (items: IndexItem[], category: string, type: string): IndexItem[] => {
  return items.filter(item => item.category === category && item.type === type);
};

export const getItemsByBrand = (items: IndexItem[], brand: string): IndexItem[] => {
  return items.filter(item => item.brand === brand);
};

export const getItemsByModel = (items: IndexItem[], model: string): IndexItem[] => {
  return items.filter(item => item.model === model);
};




